In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/upi_transactions_2024.csv")

In [3]:
df['fraud_flag'].value_counts()

fraud_flag
0    249520
1       480
Name: count, dtype: int64

In [4]:
df['fraud_flag'].value_counts(normalize=True) * 100

fraud_flag
0    99.808
1     0.192
Name: proportion, dtype: float64

In [5]:
df['transaction_status'].value_counts()

transaction_status
SUCCESS    237624
FAILED      12376
Name: count, dtype: int64

In [6]:
pd.crosstab(df['transaction type'], df['fraud_flag'])

fraud_flag             0    1
transaction type
Bill Payment       37291   77
P2M                87493  167
P2P               112239  206
Recharge           12497   30

In [7]:
df['device_type'].value_counts()

device_type
Android    187777
iOS         49613
Web         12610
Name: count, dtype: int64

In [8]:
pd.crosstab(df['device_type'], df['fraud_flag'])

fraud_flag        0    1
device_type
Android      187413  364
Web           12584   26
iOS           49523   90

In [9]:
df['network_type'].value_counts()

network_type
4G      149813
5G       62582
WiFi     25134
3G       12471
Name: count, dtype: int64

In [10]:
pd.crosstab(df['network_type'], df['fraud_flag'])

fraud_flag         0    1
network_type
3G             12447   24
4G            149531  282
5G             62467  115
WiFi           25075   59

In [11]:
df['amount (INR)'].describe()

count    250000.000000
mean       1311.756036
std        1848.059224
min          10.000000
25%         288.000000
50%         629.000000
75%        1596.000000
max       42099.000000
Name: amount (INR), dtype: float64

In [12]:
df.groupby('fraud_flag')['amount (INR)'].describe()

,count,mean,std,min,25%,50%,75%,max
fraud_flag,,,,,,,,
0,249520.0,1311.395391,1847.210565,10.0,288.0,629.0,1596.0,42099.0
1,480.0,1499.231250,2240.707939,28.0,260.0,618.5,1673.5,17718.0

In [13]:
df['hour_of_day'].describe()

count    250000.000000
mean         14.681032
std           5.188304
min           0.000000
25%          11.000000
50%          15.000000
75%          19.000000
max          23.000000
Name: hour_of_day, dtype: float64

In [14]:
pd.crosstab(df['hour_of_day'], df['fraud_flag'])

fraud_flag       0   1
hour_of_day
0             3380   8
1             2238   6
2             1682   3
3             1310   4
4             1246   1
5             1741   1
6             3496   5
7             5617  13
8             8331  18
9            10430  20
10           13884  20
11           16301  27
12           17486  30
13           15013  25
14           11451  21
15           12592  32
16           13961  31
17           18303  37
18           20033  31
19           21189  43
20           18469  37
21           16218  35
22            9341  23
23            5808   9

In [15]:
df['fraud_flag'].value_counts()

fraud_flag
0    249520
1       480
Name: count, dtype: int64

In [16]:
df['fraud_flag'].value_counts(normalize=True) * 100

fraud_flag
0    99.808
1     0.192
Name: proportion, dtype: float64

In [17]:
df['transaction_status'].value_counts()

transaction_status
SUCCESS    237624
FAILED      12376
Name: count, dtype: int64

In [18]:
pd.crosstab(df['transaction_status'], df['fraud_flag'])

fraud_flag               0    1
transaction_status
FAILED               12355   21
SUCCESS             237165  459

In [19]:
df['transaction type'].value_counts()

transaction type
P2P             112445
P2M              87660
Bill Payment     37368
Recharge         12527
Name: count, dtype: int64

In [20]:
pd.crosstab(df['transaction type'], df['fraud_flag'])

fraud_flag             0    1
transaction type
Bill Payment       37291   77
P2M                87493  167
P2P               112239  206
Recharge           12497   30

In [21]:
df['device_type'].value_counts()

device_type
Android    187777
iOS         49613
Web         12610
Name: count, dtype: int64

In [22]:
pd.crosstab(df['device_type'], df['fraud_flag'])

fraud_flag        0    1
device_type
Android      187413  364
Web           12584   26
iOS           49523   90

In [23]:
df.groupby('fraud_flag')['amount (INR)'].describe()

,count,mean,std,min,25%,50%,75%,max
fraud_flag,,,,,,,,
0,249520.0,1311.395391,1847.210565,10.0,288.0,629.0,1596.0,42099.0
1,480.0,1499.231250,2240.707939,28.0,260.0,618.5,1673.5,17718.0

In [24]:
pd.crosstab(df['hour_of_day'], df['fraud_flag'])

fraud_flag       0   1
hour_of_day
0             3380   8
1             2238   6
2             1682   3
3             1310   4
4             1246   1
5             1741   1
6             3496   5
7             5617  13
8             8331  18
9            10430  20
10           13884  20
11           16301  27
12           17486  30
13           15013  25
14           11451  21
15           12592  32
16           13961  31
17           18303  37
18           20033  31
19           21189  43
20           18469  37
21           16218  35
22            9341  23
23            5808   9

In [25]:
hour_analysis = pd.crosstab(df['hour_of_day'], df['fraud_flag'])

In [26]:
hour_analysis['total_transactions'] = (
    hour_analysis[0] + hour_analysis[1]
)

hour_analysis['fraud_rate'] = (
    hour_analysis[1] /
    hour_analysis['total_transactions']
) * 100

hour_analysis

fraud_flag       0   1  total_transactions  fraud_rate
hour_of_day
0             3380   8                3388    0.236128
1             2238   6                2244    0.267380
2             1682   3                1685    0.178042
3             1310   4                1314    0.304414
4             1246   1                1247    0.080192
5             1741   1                1742    0.057405
6             3496   5                3501    0.142816
7             5617  13                5630    0.230906
8             8331  18                8349    0.215595
9            10430  20               10450    0.191388
10           13884  20               13904    0.143843
11           16301  27               16328    0.165360
12           17486  30               17516    0.171272
13           15013  25               15038    0.166246
14           11451  21               11472    0.183054
15           12592  32               12624    0.253485
16           13961  31               13992    0.221555
17           18303  37               18340    0.201745
18           20033  31               20064    0.154506
19           21189  43               21232    0.202524
20           18469  37               18506    0.199935
21           16218  35               16253    0.215345
22            9341  23                9364    0.245622
23            5808   9                5817    0.154719

In [27]:
hour_analysis.sort_values(
    'fraud_rate',
    ascending=False
)

fraud_flag       0   1  total_transactions  fraud_rate
hour_of_day
3             1310   4                1314    0.304414
1             2238   6                2244    0.267380
15           12592  32               12624    0.253485
22            9341  23                9364    0.245622
0             3380   8                3388    0.236128
7             5617  13                5630    0.230906
16           13961  31               13992    0.221555
8             8331  18                8349    0.215595
21           16218  35               16253    0.215345
19           21189  43               21232    0.202524
17           18303  37               18340    0.201745
20           18469  37               18506    0.199935
9            10430  20               10450    0.191388
14           11451  21               11472    0.183054
2             1682   3                1685    0.178042
12           17486  30               17516    0.171272
13           15013  25               15038    0.166246
11           16301  27               16328    0.165360
23            5808   9                5817    0.154719
18           20033  31               20064    0.154506
10           13884  20               13904    0.143843
6             3496   5                3501    0.142816
4             1246   1                1247    0.080192
5             1741   1                1742    0.057405

In [28]:
df['timestamp'] = pd.to_datetime(df['timestamp'])

In [29]:
df.dtypes

transaction id                   str
timestamp             datetime64[us]
transaction type                 str
merchant_category                str
amount (INR)                   int64
transaction_status               str
sender_age_group                 str
receiver_age_group               str
sender_state                     str
sender_bank                      str
receiver_bank                    str
device_type                      str
network_type                     str
fraud_flag                     int64
hour_of_day                    int64
day_of_week                      str
is_weekend                     int64
dtype: object

In [30]:
df['timestamp'].isnull().sum()

np.int64(0)

In [31]:
print("First transaction:", df['timestamp'].min())
print("Last transaction:", df['timestamp'].max())

First transaction: 2024-01-01 00:05:10
Last transaction: 2024-12-30 23:55:40

In [32]:
print("Number of unique dates:", df['timestamp'].dt.date.nunique())

Number of unique dates: 365

In [33]:
print("Amount <= 0:", (df['amount (INR)'] <= 0).sum())
print("Invalid fraud flags:", (~df['fraud_flag'].isin([0, 1])).sum())
print("Invalid hours:", ((df['hour_of_day'] < 0) | (df['hour_of_day'] > 23)).sum())
print("Invalid weekend flags:", (~df['is_weekend'].isin([0, 1])).sum())

Amount <= 0: 0
Invalid fraud flags: 0
Invalid hours: 0
Invalid weekend flags: 0

In [34]:
categorical_columns = [
    'transaction type',
    'merchant_category',
    'transaction_status',
    'sender_age_group',
    'receiver_age_group',
    'sender_state',
    'sender_bank',
    'receiver_bank',
    'device_type',
    'network_type',
    'day_of_week'
]

for column in categorical_columns:
    print(f"\n{column}")
    print("Unique values:", df[column].nunique())
    print("Missing values:", df[column].isnull().sum())
    print(df[column].unique())

transaction type
Unique values: 4
Missing values: 0
<StringArray>
['P2P', 'P2M', 'Bill Payment', 'Recharge']
Length: 4, dtype: str

merchant_category
Unique values: 10
Missing values: 0
<StringArray>
['Entertainment',       'Grocery',          'Fuel',      'Shopping',
          'Food',         'Other',     'Utilities',     'Transport',
    'Healthcare',     'Education']
Length: 10, dtype: str

transaction_status
Unique values: 2
Missing values: 0
<StringArray>
['SUCCESS', 'FAILED']
Length: 2, dtype: str

sender_age_group
Unique values: 5
Missing values: 0
<StringArray>
['26-35', '36-45', '46-55', '56+', '18-25']
Length: 5, dtype: str

receiver_age_group
Unique values: 5
Missing values: 0
<StringArray>
['18-25', '26-35', '36-45', '46-55', '56+']
Length: 5, dtype: str

sender_state
Unique values: 10
Missing values: 0
<StringArray>
[         'Delhi',  'Uttar Pradesh',      'Karnataka',      'Telangana',
    'Maharashtra',        'Gujarat',      'Rajasthan',     'Tamil Nadu',
    'West Bengal', 'Andhra Pradesh']
Length: 10, dtype: str

sender_bank
Unique values: 8
Missing values: 0
<StringArray>
['Axis', 'ICICI', 'Yes Bank', 'IndusInd', 'HDFC', 'Kotak', 'SBI', 'PNB']
Length: 8, dtype: str

receiver_bank
Unique values: 8
Missing values: 0
<StringArray>
['SBI', 'Axis', 'PNB', 'Yes Bank', 'IndusInd', 'HDFC', 'Kotak', 'ICICI']
Length: 8, dtype: str

device_type
Unique values: 3
Missing values: 0
<StringArray>
['Android', 'iOS', 'Web']
Length: 3, dtype: str

network_type
Unique values: 4
Missing values: 0
<StringArray>
['4G', '5G', 'WiFi', '3G']
Length: 4, dtype: str

day_of_week
Unique values: 7
Missing values: 0
<StringArray>
['Tuesday', 'Thursday', 'Sunday', 'Monday', 'Saturday', 'Wednesday', 'Friday']
Length: 7, dtype: str

In [35]:
processed_path = "../data/processed/upi_transactions_clean.csv"

df.to_csv(processed_path, index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [36]:
transaction_type_analysis = (
    df.groupby('transaction type')['fraud_flag']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'total_transactions',
        'sum': 'fraud_transactions'
    })
)

transaction_type_analysis['fraud_rate'] = (
    transaction_type_analysis['fraud_transactions']
    / transaction_type_analysis['total_transactions']
) * 100

transaction_type_analysis.sort_values(
    'fraud_rate',
    ascending=False
)

                  total_transactions  fraud_transactions  fraud_rate
transaction type
Recharge                       12527                  30    0.239483
Bill Payment                   37368                  77    0.206059
P2M                            87660                 167    0.190509
P2P                           112445                 206    0.183201

In [37]:
device_analysis = (
    df.groupby('device_type')['fraud_flag']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'total_transactions',
        'sum': 'fraud_transactions'
    })
)

device_analysis['fraud_rate'] = (
    device_analysis['fraud_transactions']
    / device_analysis['total_transactions']
) * 100

device_analysis.sort_values(
    'fraud_rate',
    ascending=False
)

             total_transactions  fraud_transactions  fraud_rate
device_type
Web                       12610                  26    0.206186
Android                  187777                 364    0.193847
iOS                       49613                  90    0.181404

In [38]:
merchant_analysis = (
    df.groupby('merchant_category')['fraud_flag']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'total_transactions',
        'sum': 'fraud_transactions'
    })
)

merchant_analysis['fraud_rate'] = (
    merchant_analysis['fraud_transactions']
    / merchant_analysis['total_transactions']
) * 100

merchant_analysis.sort_values(
    'fraud_rate',
    ascending=False
)

                   total_transactions  fraud_transactions  fraud_rate
merchant_category
Transport                       20105                  43    0.213877
Education                        7598                  16    0.210582
Shopping                        29872                  62    0.207552
Other                           24828                  50    0.201386
Entertainment                   20103                  40    0.198975
Food                            37464                  73    0.194854
Fuel                            25063                  48    0.191517
Grocery                         49966                  94    0.188128
Healthcare                      12663                  21    0.165837
Utilities                       22338                  33    0.147730

In [39]:
network_analysis = (
    df.groupby('network_type')['fraud_flag']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'total_transactions',
        'sum': 'fraud_transactions'
    })
)

network_analysis['fraud_rate'] = (
    network_analysis['fraud_transactions']
    / network_analysis['total_transactions']
) * 100

network_analysis.sort_values(
    'fraud_rate',
    ascending=False
)

              total_transactions  fraud_transactions  fraud_rate
network_type
WiFi                       25134                  59    0.234742
3G                         12471                  24    0.192446
4G                        149813                 282    0.188235
5G                         62582                 115    0.183759

In [40]:
df['amount_band'] = pd.cut(
    df['amount (INR)'],
    bins=[0, 500, 1000, 2500, 5000, 10000, float('inf')],
    labels=[
        '₹0–500',
        '₹501–1,000',
        '₹1,001–2,500',
        '₹2,501–5,000',
        '₹5,001–10,000',
        '₹10,000+'
    ]
)

In [41]:
amount_analysis = (
    df.groupby('amount_band', observed=True)['fraud_flag']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'total_transactions',
        'sum': 'fraud_transactions'
    })
)

amount_analysis['fraud_rate'] = (
    amount_analysis['fraud_transactions']
    / amount_analysis['total_transactions']
) * 100

amount_analysis

               total_transactions  fraud_transactions  fraud_rate
amount_band
₹0–500                     106624                 211    0.197892
₹501–1,000                  51037                  85    0.166546
₹1,001–2,500                55436                  98    0.176780
₹2,501–5,000                25947                  53    0.204263
₹5,001–10,000                9151                  27    0.295050
₹10,000+                     1805                   6    0.332410

In [42]:
state_analysis = (
    df.groupby('sender_state')['fraud_flag']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'total_transactions',
        'sum': 'fraud_transactions'
    })
)

state_analysis['fraud_rate'] = (
    state_analysis['fraud_transactions']
    / state_analysis['total_transactions']
) * 100

state_analysis.sort_values('fraud_rate', ascending=False)

                total_transactions  fraud_transactions  fraud_rate
sender_state
Karnataka                    29756                  69    0.231886
Rajasthan                    19981                  46    0.230219
Gujarat                      20061                  43    0.214346
Delhi                        24870                  50    0.201045
Maharashtra                  37427                  71    0.189703
West Bengal                  19972                  35    0.175245
Andhra Pradesh               20006                  35    0.174948
Telangana                    22435                  39    0.173836
Uttar Pradesh                30125                  52    0.172614
Tamil Nadu                   25367                  40    0.157685

In [43]:
weekend_analysis = (
    df.groupby('is_weekend')['fraud_flag']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'total_transactions',
        'sum': 'fraud_transactions'
    })
)

weekend_analysis['fraud_rate'] = (
    weekend_analysis['fraud_transactions']
    / weekend_analysis['total_transactions']
) * 100

weekend_analysis

            total_transactions  fraud_transactions  fraud_rate
is_weekend
0                       178663                 337    0.188623
1                        71337                 143    0.200457

In [44]:
sender_age_analysis = (
    df.groupby('sender_age_group')['fraud_flag']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'total_transactions',
        'sum': 'fraud_transactions'
    })
)

sender_age_analysis['fraud_rate'] = (
    sender_age_analysis['fraud_transactions']
    / sender_age_analysis['total_transactions']
) * 100

sender_age_analysis.sort_values('fraud_rate', ascending=False)

                  total_transactions  fraud_transactions  fraud_rate
sender_age_group
18-25                          62345                 143    0.229369
56+                            12509                  27    0.215845
26-35                          87432                 163    0.186431
36-45                          62873                 116    0.184499
46-55                          24841                  31    0.124794

In [45]:
receiver_age_analysis = (
    df.groupby('receiver_age_group')['fraud_flag']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'total_transactions',
        'sum': 'fraud_transactions'
    })
)

receiver_age_analysis['fraud_rate'] = (
    receiver_age_analysis['fraud_transactions']
    / receiver_age_analysis['total_transactions']
) * 100

receiver_age_analysis.sort_values('fraud_rate', ascending=False)

                    total_transactions  fraud_transactions  fraud_rate
receiver_age_group
46-55                            24823                  57    0.229626
18-25                            62611                 132    0.210826
36-45                            62151                 125    0.201123
26-35                            87864                 148    0.168442
56+                              12551                  18    0.143415

In [46]:
type_device_analysis = (
    df.groupby(['transaction type', 'device_type'])['fraud_flag']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'total_transactions',
        'sum': 'fraud_transactions'
    })
)

type_device_analysis['fraud_rate'] = (
    type_device_analysis['fraud_transactions']
    / type_device_analysis['total_transactions']
) * 100

type_device_analysis.sort_values('fraud_rate', ascending=False)

                              total_transactions  fraud_transactions  \
transaction type device_type
Recharge         Android                    9387                  26
P2M              Web                        4393                  12
Bill Payment     Android                   28056                  59
P2P              iOS                       22474                  47
Bill Payment     iOS                        7387                  15
P2M              Android                   65998                 131
P2P              Web                        5635                  11
                 Android                   84336                 148
Recharge         iOS                        2483                   4
Bill Payment     Web                        1925                   3
P2M              iOS                       17269                  24
Recharge         Web                         657                   0

                              fraud_rate
transaction type device_type
Recharge         Android        0.276979
P2M              Web            0.273162
Bill Payment     Android        0.210294
P2P              iOS            0.209131
Bill Payment     iOS            0.203059
P2M              Android        0.198491
P2P              Web            0.195209
                 Android        0.175489
Recharge         iOS            0.161095
Bill Payment     Web            0.155844
P2M              iOS            0.138977
Recharge         Web            0.000000

In [47]:
df['time_period'] = pd.cut(
    df['hour_of_day'],
    bins=[-1, 5, 11, 17, 23],
    labels=['Night', 'Morning', 'Afternoon', 'Evening']
)

In [48]:
time_analysis = (
    df.groupby('time_period', observed=True)['fraud_flag']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'total_transactions',
        'sum': 'fraud_transactions'
    })
)

time_analysis['fraud_rate'] = (
    time_analysis['fraud_transactions']
    / time_analysis['total_transactions']
) * 100

time_analysis

             total_transactions  fraud_transactions  fraud_rate
time_period
Night                     11620                  23    0.197935
Morning                   58162                 103    0.177092
Afternoon                 88982                 176    0.197793
Evening                   91236                 178    0.195098

In [49]:
overall_fraud_rate = df['fraud_flag'].mean() * 100

print(f"Overall fraud rate: {overall_fraud_rate:.3f}%")

Overall fraud rate: 0.192%

In [50]:
transaction_type_risk = (
    df.groupby('transaction type')['fraud_flag']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'total_transactions',
        'sum': 'fraud_transactions'
    })
)

transaction_type_risk['fraud_rate'] = (
    transaction_type_risk['fraud_transactions']
    / transaction_type_risk['total_transactions']
) * 100

transaction_type_risk['relative_risk'] = (
    transaction_type_risk['fraud_rate']
    / overall_fraud_rate
)

transaction_type_risk.sort_values('relative_risk', ascending=False)

,total_transactions,fraud_transactions,fraud_rate,relative_risk
transaction type,,,,
Recharge,12527,30,0.239483,1.247306
Bill Payment,37368,77,0.206059,1.073222
P2M,87660,167,0.190509,0.992233
P2P,112445,206,0.183201,0.954170

In [51]:
device_risk = (
    df.groupby('device_type')['fraud_flag']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'total_transactions',
        'sum': 'fraud_transactions'
    })
)

device_risk['fraud_rate'] = (
    device_risk['fraud_transactions']
    / device_risk['total_transactions']
) * 100

device_risk['relative_risk'] = (
    device_risk['fraud_rate']
    / overall_fraud_rate
)

device_risk.sort_values('relative_risk', ascending=False)

             total_transactions  fraud_transactions  fraud_rate  relative_risk
device_type
Web                       12610                  26    0.206186       1.073883
Android                  187777                 364    0.193847       1.009620
iOS                       49613                  90    0.181404       0.944813

In [52]:
network_risk = (
    df.groupby('network_type')['fraud_flag']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'total_transactions',
        'sum': 'fraud_transactions'
    })
)

network_risk['fraud_rate'] = (
    network_risk['fraud_transactions']
    / network_risk['total_transactions']
) * 100

network_risk['relative_risk'] = (
    network_risk['fraud_rate']
    / overall_fraud_rate
)

network_risk.sort_values('relative_risk', ascending=False)

,total_transactions,fraud_transactions,fraud_rate,relative_risk
network_type,,,,
WiFi,25134,59,0.234742,1.222613
3G,12471,24,0.192446,1.002325
4G,149813,282,0.188235,0.980389
5G,62582,115,0.183759,0.957078

In [53]:
device_risk

             total_transactions  fraud_transactions  fraud_rate  relative_risk
device_type
Android                  187777                 364    0.193847       1.009620
Web                       12610                  26    0.206186       1.073883
iOS                       49613                  90    0.181404       0.944813

In [54]:
type_device_risk = (
    df.groupby(['transaction type', 'device_type'])['fraud_flag']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'total_transactions',
        'sum': 'fraud_transactions'
    })
)

type_device_risk['fraud_rate'] = (
    type_device_risk['fraud_transactions']
    / type_device_risk['total_transactions']
) * 100

type_device_risk['relative_risk'] = (
    type_device_risk['fraud_rate']
    / overall_fraud_rate
)

type_device_risk = type_device_risk.sort_values(
    'relative_risk',
    ascending=False
)

type_device_risk

                              total_transactions  fraud_transactions  \
transaction type device_type
Recharge         Android                    9387                  26
P2M              Web                        4393                  12
Bill Payment     Android                   28056                  59
P2P              iOS                       22474                  47
Bill Payment     iOS                        7387                  15
P2M              Android                   65998                 131
P2P              Web                        5635                  11
                 Android                   84336                 148
Recharge         iOS                        2483                   4
Bill Payment     Web                        1925                   3
P2M              iOS                       17269                  24
Recharge         Web                         657                   0

                              fraud_rate  relative_risk
transaction type device_type
Recharge         Android        0.276979       1.442598
P2M              Web            0.273162       1.422718
Bill Payment     Android        0.210294       1.095280
P2P              iOS            0.209131       1.089222
Bill Payment     iOS            0.203059       1.057601
P2M              Android        0.198491       1.033807
P2P              Web            0.195209       1.016711
                 Android        0.175489       0.914003
Recharge         iOS            0.161095       0.839039
Bill Payment     Web            0.155844       0.811688
P2M              iOS            0.138977       0.723840
Recharge         Web            0.000000       0.000000

In [55]:
type_network_risk = (
    df.groupby(['transaction type', 'network_type'])['fraud_flag']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'total_transactions',
        'sum': 'fraud_transactions'
    })
)

type_network_risk['fraud_rate'] = (
    type_network_risk['fraud_transactions']
    / type_network_risk['total_transactions']
) * 100

type_network_risk['relative_risk'] = (
    type_network_risk['fraud_rate']
    / overall_fraud_rate
)

type_network_risk = type_network_risk.sort_values(
    'relative_risk',
    ascending=False
)

type_network_risk

                               total_transactions  fraud_transactions  \
transaction type network_type
Recharge         WiFi                        1226                   5
                 3G                           598                   2
Bill Payment     3G                          1926                   6
                 WiFi                        3715                  11
P2M              WiFi                        8781                  24
Recharge         4G                          7538                  18
P2M              3G                          4334                  10
P2P              5G                         28146                  58
Bill Payment     4G                         22423                  45
P2P              4G                         67274                 123
P2M              4G                         52578                  96
                 5G                         21967                  37
P2P              WiFi                       11412                  19
Bill Payment     5G                          9304                  15
Recharge         5G                          3165                   5
P2P              3G                          5613                   6

                               fraud_rate  relative_risk
transaction type network_type
Recharge         WiFi            0.407830       2.124116
                 3G              0.334448       1.741918
Bill Payment     3G              0.311526       1.622534
                 WiFi            0.296097       1.542171
P2M              WiFi            0.273317       1.423528
Recharge         4G              0.238790       1.243699
P2M              3G              0.230734       1.201738
P2P              5G              0.206068       1.073273
Bill Payment     4G              0.200687       1.045244
P2P              4G              0.182834       0.952262
P2M              4G              0.182586       0.950968
                 5G              0.168434       0.877263
P2P              WiFi            0.166491       0.867143
Bill Payment     5G              0.161221       0.839693
Recharge         5G              0.157978       0.822801
P2P              3G              0.106895       0.556743

In [56]:
reliable_type_network = type_network_risk[
    type_network_risk['total_transactions'] >= 5000
].sort_values(
    'relative_risk',
    ascending=False
)

reliable_type_network

                               total_transactions  fraud_transactions  \
transaction type network_type
P2M              WiFi                        8781                  24
Recharge         4G                          7538                  18
P2P              5G                         28146                  58
Bill Payment     4G                         22423                  45
P2P              4G                         67274                 123
P2M              4G                         52578                  96
                 5G                         21967                  37
P2P              WiFi                       11412                  19
Bill Payment     5G                          9304                  15
P2P              3G                          5613                   6

                               fraud_rate  relative_risk
transaction type network_type
P2M              WiFi            0.273317       1.423528
Recharge         4G              0.238790       1.243699
P2P              5G              0.206068       1.073273
Bill Payment     4G              0.200687       1.045244
P2P              4G              0.182834       0.952262
P2M              4G              0.182586       0.950968
                 5G              0.168434       0.877263
P2P              WiFi            0.166491       0.867143
Bill Payment     5G              0.161221       0.839693
P2P              3G              0.106895       0.556743

In [57]:
status_risk = (
    df.groupby('transaction_status')['fraud_flag']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'total_transactions',
        'sum': 'fraud_transactions'
    })
)

status_risk['fraud_rate'] = (
    status_risk['fraud_transactions']
    / status_risk['total_transactions']
) * 100

status_risk['relative_risk'] = (
    status_risk['fraud_rate']
    / overall_fraud_rate
)

status_risk.sort_values('relative_risk', ascending=False)

,total_transactions,fraud_transactions,fraud_rate,relative_risk
transaction_status,,,,
SUCCESS,237624,459,0.193162,1.006054
FAILED,12376,21,0.169683,0.883767

In [58]:
import numpy as np

df['amount_log'] = np.log1p(df['amount (INR)'])

df[['amount (INR)', 'amount_log']].head()

   amount (INR)  amount_log
0           868    6.767343
1          1011    6.919684
2           477    6.169611
3          2784    7.932003
4           990    6.898715

In [59]:
df[['hour_of_day', 'time_period']].head(10)

   hour_of_day time_period
0           15   Afternoon
1            6     Morning
2           13   Afternoon
3           10     Morning
4           19     Evening
5           22     Evening
6           10     Morning
7           18     Evening
8            9     Morning
9           15   Afternoon

In [60]:
df['weekend_evening'] = (
    (df['is_weekend'] == 1) &
    (df['time_period'] == 'Evening')
).astype(int)

df[['is_weekend', 'time_period', 'weekend_evening']].head(10)

   is_weekend time_period  weekend_evening
0           0   Afternoon                0
1           0     Morning                0
2           0   Afternoon                0
3           1     Morning                0
4           0     Evening                0
5           0     Evening                0
6           0     Morning                0
7           1     Evening                1
8           0     Morning                0
9           0   Afternoon                0

In [61]:
df['high_value_flag'] = (
    df['amount (INR)'] > 5000
).astype(int)

df[['amount (INR)', 'high_value_flag']].head(10)

   amount (INR)  high_value_flag
0           868                0
1          1011                0
2           477                0
3          2784                0
4           990                0
5            91                0
6           314                0
7           264                0
8           887                0
9          3260                0

In [62]:
high_value_risk = (
    df.groupby('high_value_flag')['fraud_flag']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'total_transactions',
        'sum': 'fraud_transactions'
    })
)

high_value_risk['fraud_rate'] = (
    high_value_risk['fraud_transactions']
    / high_value_risk['total_transactions']
) * 100

high_value_risk['relative_risk'] = (
    high_value_risk['fraud_rate']
    / overall_fraud_rate
)

high_value_risk

,total_transactions,fraud_transactions,fraud_rate,relative_risk
high_value_flag,,,,
0,239044,447,0.186995,0.973932
1,10956,33,0.301205,1.568775

In [63]:
high_value_network_risk = (
    df.groupby(['high_value_flag', 'network_type'])['fraud_flag']
    .agg(['count', 'sum'])
    .rename(columns={
        'count': 'total_transactions',
        'sum': 'fraud_transactions'
    })
)

high_value_network_risk['fraud_rate'] = (
    high_value_network_risk['fraud_transactions']
    / high_value_network_risk['total_transactions']
) * 100

high_value_network_risk['relative_risk'] = (
    high_value_network_risk['fraud_rate']
    / overall_fraud_rate
)

high_value_network_risk.sort_values(
    'relative_risk',
    ascending=False
)

                              total_transactions  fraud_transactions  \
high_value_flag network_type
1               4G                          6525                  21
                5G                          2714                   8
                WiFi                        1171                   3
0               WiFi                       23963                  56
                3G                         11925                  23
1               3G                           546                   1
0               4G                        143288                 261
                5G                         59868                 107

                              fraud_rate  relative_risk
high_value_flag network_type
1               4G              0.321839       1.676245
                5G              0.294768       1.535249
                WiFi            0.256191       1.334330
0               WiFi            0.233694       1.217154
                3G              0.192872       1.004542
1               3G              0.183150       0.953907
0               4G              0.182151       0.948701
                5G              0.178727       0.930867

In [64]:
feature_path = "../data/processed/upi_transactions_feature_engineered.csv"

df.to_csv(feature_path, index=False)

print("Feature-engineered dataset saved successfully.")
print("Rows:", len(df))
print("Columns:", len(df.columns))

Feature-engineered dataset saved successfully.
Rows: 250000
Columns: 22

In [65]:
model_features = [
    'amount_log',
    'transaction type',
    'merchant_category',
    'sender_age_group',
    'receiver_age_group',
    'sender_state',
    'sender_bank',
    'receiver_bank',
    'device_type',
    'network_type',
    'hour_of_day',
    'day_of_week',
    'is_weekend',
    'time_period',
    'weekend_evening',
    'high_value_flag'
]

X = df[model_features]
y = df['fraud_flag']

print("Features shape:", X.shape)
print("Target shape:", y.shape)
print("\nTarget distribution:")
print(y.value_counts())

Features shape: (250000, 16)
Target shape: (250000,)

Target distribution:
fraud_flag
0    249520
1       480
Name: count, dtype: int64

In [66]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)

print("\nTraining target distribution:")
print(y_train.value_counts())

print("\nTesting target distribution:")
print(y_test.value_counts())

Training features: (200000, 16)
Testing features: (50000, 16)

Training target distribution:
fraud_flag
0    199616
1       384
Name: count, dtype: int64

Testing target distribution:
fraud_flag
0    49904
1       96
Name: count, dtype: int64

In [67]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

categorical_features = [
    'transaction type',
    'merchant_category',
    'sender_age_group',
    'receiver_age_group',
    'sender_state',
    'sender_bank',
    'receiver_bank',
    'device_type',
    'network_type',
    'day_of_week',
    'time_period'
]

numerical_features = [
    'amount_log',
    'hour_of_day',
    'is_weekend',
    'weekend_evening',
    'high_value_flag'
]

preprocessor = ColumnTransformer(
    transformers=[
        ('categorical', OneHotEncoder(handle_unknown='ignore'), categorical_features),
        ('numerical', 'passthrough', numerical_features)
    ]
)

print("Categorical features:", len(categorical_features))
print("Numerical features:", len(numerical_features))

Categorical features: 11
Numerical features: 5

In [68]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

logistic_model = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('classifier', LogisticRegression(
            class_weight='balanced',
            max_iter=1000,
            random_state=42
        ))
    ]
)

print("Logistic Regression pipeline created successfully.")

Logistic Regression pipeline created successfully.

In [69]:
logistic_model.fit(X_train, y_train)

print("Logistic Regression model trained successfully.")

Logistic Regression model trained successfully.

In [70]:
y_pred = logistic_model.predict(X_test)

y_proba = logistic_model.predict_proba(X_test)[:, 1]

print("Predictions generated successfully.")
print("Predicted fraud cases:", y_pred.sum())

Predictions generated successfully.
Predicted fraud cases: 20564

In [71]:
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    roc_auc_score,
    average_precision_score
)

cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

print("\nClassification Report:")
print(classification_report(y_test, y_pred, digits=4))

print("ROC-AUC:", round(roc_auc_score(y_test, y_proba), 4))
print("PR-AUC:", round(average_precision_score(y_test, y_proba), 4))

Confusion Matrix:
[[29377 20527]
 [   59    37]]

Classification Report:
              precision    recall  f1-score   support

           0     0.9980    0.5887    0.7405     49904
           1     0.0018    0.3854    0.0036        96

    accuracy                         0.5883     50000
   macro avg     0.4999    0.4870    0.3721     50000
weighted avg     0.9961    0.5883    0.7391     50000

ROC-AUC: 0.4853
PR-AUC: 0.0018

In [72]:
from sklearn.ensemble import RandomForestClassifier

random_forest_model = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('classifier', RandomForestClassifier(
            n_estimators=200,
            class_weight='balanced',
            random_state=42,
            n_jobs=-1
        ))
    ]
)

print("Random Forest pipeline created successfully.")

Random Forest pipeline created successfully.

In [73]:
random_forest_model.fit(X_train, y_train)

print("Random Forest model trained successfully.")

Random Forest model trained successfully.

In [74]:
rf_pred = random_forest_model.predict(X_test)

rf_proba = random_forest_model.predict_proba(X_test)[:, 1]

print("Predictions generated successfully.")
print("Predicted fraud cases:", rf_pred.sum())

Predictions generated successfully.
Predicted fraud cases: 0

In [75]:
rf_cm = confusion_matrix(y_test, rf_pred)

print("Confusion Matrix:")
print(rf_cm)

print("\nClassification Report:")
print(classification_report(y_test, rf_pred, digits=4))

print("ROC-AUC:", round(roc_auc_score(y_test, rf_proba), 4))
print("PR-AUC:", round(average_precision_score(y_test, rf_proba), 4))

Confusion Matrix:
[[49904     0]
 [   96     0]]

Classification Report:
              precision    recall  f1-score   support

           0     0.9981    1.0000    0.9990     49904
           1     0.0000    0.0000    0.0000        96

    accuracy                         0.9981     50000
   macro avg     0.4990    0.5000    0.4995     50000
weighted avg     0.9962    0.9981    0.9971     50000

ROC-AUC: 0.4776
PR-AUC: 0.0023

c:\Users\Varun  j  upadhyay\OneDrive\Desktop\UPI_Transaction_Risk_Intelligence\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Varun  j  upadhyay\OneDrive\Desktop\UPI_Transaction_Risk_Intelligence\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Varun  j  upadhyay\OneDrive\Desktop\UPI_Transaction_Risk_Intelligence\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [76]:
print("Minimum probability:", rf_proba.min())
print("Maximum probability:", rf_proba.max())
print("Mean probability:", rf_proba.mean())

print("\nHighest 20 fraud probabilities:")
print(sorted(rf_proba, reverse=True)[:20])

Minimum probability: 0.0
Maximum probability: 0.42
Mean probability: 0.0052201999999999995

Highest 20 fraud probabilities:
[np.float64(0.42), np.float64(0.285), np.float64(0.25), np.float64(0.25), np.float64(0.245), np.float64(0.24), np.float64(0.22), np.float64(0.22), np.float64(0.215), np.float64(0.205), np.float64(0.195), np.float64(0.19), np.float64(0.175), np.float64(0.165), np.float64(0.155), np.float64(0.15), np.float64(0.15), np.float64(0.145), np.float64(0.14), np.float64(0.135)]

In [78]:
import numpy as np

normal_proba = rf_proba[y_test == 0]
fraud_proba = rf_proba[y_test == 1]

print("Normal transactions:")
print("Mean probability:", normal_proba.mean())
print("Median probability:", np.median(normal_proba))

print("\nActual fraud transactions:")
print("Mean probability:", fraud_proba.mean())
print("Median probability:", np.median(fraud_proba))

print("\nHighest probability among actual fraud:")
print(fraud_proba.max())

print("\nHighest probability among normal:")
print(normal_proba.max())

Normal transactions:
Mean probability: 0.005219521481243989
Median probability: 0.0

Actual fraud transactions:
Mean probability: 0.005572916666666667
Median probability: 0.0

Highest probability among actual fraud:
0.125

Highest probability among normal:
0.42

In [79]:
print("Fraud rate by high-value flag:")
print(
    df.groupby('high_value_flag')['fraud_flag']
      .agg(['count', 'sum', 'mean'])
)

print("\nFraud rate by weekend:")
print(
    df.groupby('is_weekend')['fraud_flag']
      .agg(['count', 'sum', 'mean'])
)

print("\nFraud rate by time period:")
print(
    df.groupby('time_period', observed=True)['fraud_flag']
      .agg(['count', 'sum', 'mean'])
)

Fraud rate by high-value flag:
                  count  sum      mean
high_value_flag
0                239044  447  0.001870
1                 10956   33  0.003012

Fraud rate by weekend:
             count  sum      mean
is_weekend
0           178663  337  0.001886
1            71337  143  0.002005

Fraud rate by time period:
             count  sum      mean
time_period
Night        11620   23  0.001979
Morning      58162  103  0.001771
Afternoon    88982  176  0.001978
Evening      91236  178  0.001951

In [80]:
overall_rate = df['fraud_flag'].mean()

risk_indicators = {
    'High Value (>₹5,000)': df['high_value_flag'] == 1,
    'Recharge': df['transaction type'] == 'Recharge',
    'WiFi': df['network_type'] == 'WiFi',
    'Weekend': df['is_weekend'] == 1,
    'Evening': df['time_period'] == 'Evening'
}

for name, condition in risk_indicators.items():
    rate = df.loc[condition, 'fraud_flag'].mean()
    relative_risk = rate / overall_rate

    print(
        f"{name}: "
        f"Fraud rate = {rate:.4%}, "
        f"Relative risk = {relative_risk:.2f}x"
    )

High Value (>₹5,000): Fraud rate = 0.3012%, Relative risk = 1.57x
Recharge: Fraud rate = 0.2395%, Relative risk = 1.25x
WiFi: Fraud rate = 0.2347%, Relative risk = 1.22x
Weekend: Fraud rate = 0.2005%, Relative risk = 1.04x
Evening: Fraud rate = 0.1951%, Relative risk = 1.02x

In [81]:
df['risk_score'] = (
    df['high_value_flag'] * 3
    + (df['transaction type'] == 'Recharge').astype(int) * 2
    + (df['network_type'] == 'WiFi').astype(int) * 2
    + df['is_weekend'] * 1
    + (df['time_period'] == 'Evening').astype(int) * 1
)

print(df['risk_score'].value_counts().sort_index())

risk_score
0    92830
1    89938
2    36790
3    19087
4     8112
5     2188
6      829
7      192
8       28
9        6
Name: count, dtype: int64

In [82]:
risk_analysis = (
    df.groupby('risk_score')['fraud_flag']
      .agg(
          total_transactions='count',
          fraud_cases='sum',
          fraud_rate='mean'
      )
      .reset_index()
)

risk_analysis['fraud_rate_pct'] = risk_analysis['fraud_rate'] * 100

print(risk_analysis)

   risk_score  total_transactions  fraud_cases  fraud_rate  fraud_rate_pct
0           0               92830          167    0.001799        0.179899
1           1               89938          155    0.001723        0.172341
2           2               36790           75    0.002039        0.203860
3           3               19087           50    0.002620        0.261958
4           4                8112           23    0.002835        0.283531
5           5                2188            9    0.004113        0.411335
6           6                 829            1    0.001206        0.120627
7           7                 192            0    0.000000        0.000000
8           8                  28            0    0.000000        0.000000
9           9                   6            0    0.000000        0.000000

In [83]:
print("\nRisk score summary:")
print(
    risk_analysis[
        ['risk_score', 'total_transactions', 'fraud_cases', 'fraud_rate_pct']
    ].to_string(index=False)
)

Risk score summary:
 risk_score  total_transactions  fraud_cases  fraud_rate_pct
          0               92830          167        0.179899
          1               89938          155        0.172341
          2               36790           75        0.203860
          3               19087           50        0.261958
          4                8112           23        0.283531
          5                2188            9        0.411335
          6                 829            1        0.120627
          7                 192            0        0.000000
          8                  28            0        0.000000
          9                   6            0        0.000000

In [84]:
high_risk = df[df['risk_score'] >= 3]

print("High-risk transactions:", len(high_risk))
print("High-risk fraud cases:", high_risk['fraud_flag'].sum())

print(
    "High-risk fraud rate:",
    round(high_risk['fraud_flag'].mean() * 100, 4),
    "%"
)

print(
    "Share of all transactions:",
    round(len(high_risk) / len(df) * 100, 2),
    "%"
)

print(
    "Share of all fraud cases captured:",
    round(
        high_risk['fraud_flag'].sum() / df['fraud_flag'].sum() * 100,
        2
    ),
    "%"
)

High-risk transactions: 30442
High-risk fraud cases: 83
High-risk fraud rate: 0.2726 %
Share of all transactions: 12.18 %
Share of all fraud cases captured: 17.29 %

In [85]:
df['risk_tier'] = pd.cut(
    df['risk_score'],
    bins=[-1, 1, 3, float('inf')],
    labels=['Low', 'Medium', 'High']
)

print(df['risk_tier'].value_counts().sort_index())

risk_tier
Low       182768
Medium     55877
High       11355
Name: count, dtype: int64

In [86]:
tier_analysis = (
    df.groupby('risk_tier', observed=True)['fraud_flag']
      .agg(
          total_transactions='count',
          fraud_cases='sum',
          fraud_rate='mean'
      )
      .reset_index()
)

tier_analysis['fraud_rate_pct'] = tier_analysis['fraud_rate'] * 100

print(tier_analysis.to_string(index=False))

risk_tier  total_transactions  fraud_cases  fraud_rate  fraud_rate_pct
      Low              182768          322    0.001762        0.176180
   Medium               55877          125    0.002237        0.223706
     High               11355           33    0.002906        0.290621

In [87]:
risk_path = "../data/processed/upi_transactions_risk_scored.csv"

df.to_csv(risk_path, index=False)

print("Risk-scored dataset saved successfully.")
print("Rows:", len(df))
print("Columns:", len(df.columns))
print("File:", risk_path)

Risk-scored dataset saved successfully.
Rows: 250000
Columns: 24
File: ../data/processed/upi_transactions_risk_scored.csv